Repository RegioHelden/django-celery-token-bucket, pull requests merged in 2025-04, with the labels that each got.

#15 Renovate and migrate to reusable github workflows
  .devcontainer/compose.yaml
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/workflow.yaml
  .gitignore
  CHANGELOG.md
  Dockerfile
  HISTORY.md
  MANIFEST.in
  README.md
  compose.yaml
  django_celery_token_bucket/__init__.py
  django_celery_token_bucket/apps.py
  django_celery_token_bucket/bucket.py
  django_celery_token_bucket/decorators.py
  django_celery_token_bucket/management/commands/token_bucket_register_periodic_tasks.py
  django_celery_token_bucket/tasks.py
  django_celery_token_bucket/tests/test_bucket.py
  django_celery_token_bucket/tests/test_tasks.py
  docker-compose.yaml
  docker/settings.py
  example/__init__.py
  example/settings.py
  manage.py
  pyproject.toml
  requirements-ci.txt
  requirements-test.txt
  requirements.txt
  setup.cfg
  setup.py
  tox.ini
Labels: enhancement

#17 Remove support for EOL Python and Django releases, add support for Django 5.2, increase minimum dependency versions
  .github/workflows/workflow.yaml
  django_celery_token_bucket/bucket.py
  example/settings.py
  pyproject.toml
Labels: backwards-incompatible

#18 Release v4.0.0
  CHANGELOG.md
  pyproject.toml
Labels: skip-changelog

#19 Use specific Django version when running tests locally
  requirements-test.txt
Labels: enhancement

#20 Pin reusable workflow release
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/workflow.yaml
Labels: skip-changelog

#22 Preparations for modulesync rollout
  .sync.yml
  requirements-ci.txt
  system_dependencies.txt
Labels: infrastucture

#23 Updates from modulesync
  .devcontainer/compose.yaml
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .gitignore
  .vscode/tasks.json
  Dockerfile
  LICENSE
  compose.yaml
  example/__init__.py
  manage.py
  pyproject.toml
Labels: infrastucture

#26 Updates from modulesync
  .github/dependabot.yml
  .github/workflows/build-and-publish.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#27 Updates from modulesync
  .devcontainer/devcontainer.json
Labels: infrastucture

#28 Updates from modulesync
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#29 Updates from modulesync
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  Dockerfile
Labels: infrastucture

#31 Updates from modulesync
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#32 Updates from modulesync
  Dockerfile
Labels: infrastucture
